### ISSUE TITLE
Add a 'last answers' Tab on home page

### ISSUE THREAD

**Issue by daonb** [hasadna/open-shot#61]
And make it the default tab for returning users.

**Comment by amirnissim** [comment]
Done
https://github.com/amirnissim/okqa/commit/fcb517a9ba45578abd8d2ad7024a6b9af8677e62

**Comment by gl1000007** [comment]
should this issue be closed?

**Comment by daonb** [comment]
Why? we still don't have answers...

On 6 August 2013 13:38, Gilad L notifications@github.com wrote:

> should this issue be closed?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hasadna/open-shot/issues/61#issuecomment-22170651
> .

## 

http://yeda.us/daonb
